---
- hosts: localhost
  connection: local
  tasks:

  - name: "ec2"
    #vars:#
    #  instance : t2.micr#o
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      # key_name: "krupakar_reddy"
      # vpc_subnet_id: subnet-5ca1ab1e
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ my_access }}"
      aws_secret_key: "{{ my_secret }}"
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        Environment: Testing
    loop:
      - { image : "ami-0e1d06225679bc1c5", name: "module-1" }
      - { image : "ami-0e1d06225679bc1c5", name: "module-2" }

